"""initial schema with firebase auth

Revision ID: d27d86df8e02
Revises:
Create Date: 2026-03-24 00:10:38.751805

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d27d86df8e02"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("firebase_uid", sa.String(length=128), nullable=False))
    op.create_index(op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=False)
    op.create_unique_constraint("uq_user_tenant_firebase_uid", "users", ["tenant_id", "firebase_uid"])
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint("uq_user_tenant_firebase_uid", "users", type_="unique")
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.drop_column("users", "firebase_uid")
    # ### end Alembic commands ###
