"""add conversations and chat_messages tables

Revision ID: f097c9ef23a1
Revises: d27d86df8e02
Create Date: 2026-03-24 00:35:33.646463

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f097c9ef23a1"
down_revision: Union[str, Sequence[str], None] = "d27d86df8e02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
